version: "3.9"

services:

  postgres-db:
    image: postgres:11-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.2.4
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    links:
      - postgres-db
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=true
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.1
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

  hlm-proxy:
    image: healenium/hlm-proxy:1.2.0
    container_name: hlm-proxy
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - RECOVERY_TRIES=1
      - SCORE_CAP=.6
      - HEAL_ENABLED=true
      - SELENIUM_SERVER_URL=http://hlm-selenoid:4444/wd/hub
      - APPIUM_SERVER_URL=http://host.docker.internal:4723/wd/hub
      - HEALENIUM_SERVER_URL=http://localhost:7878
      - HEALENIUM_SERVICE=http://healenium:7878
      - IMITATE_SERVICE=http://selector-imitator:8000
    networks:
      - healenium

  chrome:
    image: selenium/node-chrome:103.0
    container_name: node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - healenium

  edge:
    image: selenium/node-edge:103.0
    container_name: node-edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - healenium

  firefox:
    image: selenium/node-firefox:101.0
    container_name: node-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - healenium

  selenium-hub:
    image: selenium/hub:4.3.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
